@startuml
'https://plantuml.com/class-diagram



class Room{
roomID: Long PK
roomName: String

}

class Seat{
seatID: Long PK
seatOrderID: Long FK
studentID: Long FK
}

class SeatOrder{
seatOrderID: Long PK
roomID: Long FK

}

class Class{
classID: Long PK
className: String
seatOrderID: Long FK
timeTableID: Long FK
}

class Student{
personID: Person PK FK
classID: Long FK
}

class Teacher{
personID: Person PK FK
classID: Long FK
}

class Absent{
absentID: Long
studentID Long
timeStart: LocalDateTime
timeEnd: LocalDateTime
lessonTime: Long
}


class TimeTable{
timeTableID: Long PK
personID: Long FK
subjectID: Long FK
day: Long
lessonTime: Long
}

class Subject{
subjectID: Long PK
name: String

}

class Table {
tableId: Long PK
row: Int
column: Int
}

Abstract Class Person{
firstName: String
lastName: String
personID: Long
}

Person *.. Student : inherit
Person *.. Teacher : inherit
TimeTable ||..|{ Subject : 1 : n
Student }|..|| Class : n : 1
TimeTable ||..|{ Class : 1 : n
Student ||..|{ Absent: 1 : n
Student ||.up.|| Seat : 1 : 1
SeatOrder }|..|| Room : n : 1
Table }|..|| SeatOrder : n : 1
Table ||..|{ Seat : 1 : n
Teacher ||..|{ TimeTable : 1 : n
SeatOrder ||..|{ TimeTable : 1 : n


@enduml