@startuml
'https://plantuml.com/class-diagram



class Room{
roomID: Long PK
roomName: String

}

class Seat{
seatID: Long PK
seatOrderID: Long FK
studentID: Long FK
}

class SeatOrder{
seatOrderID: Long PK
roomID: Long FK

}

class Class{
classID: Long PK
className: String
seatOrderID: Long FK
timeTableID: Long FK
}

class Student{
personID: Person PK FK
classID: Long FK
}

class Teacher{
personID: Person PK FK
classID: Long FK
}

class Absent{
absentID: Long
studentID Long
timeStart: LocalDateTime
timeEnd: LocalDateTime
lessonTime: Long
}


class TimeTable{
timeTableID: Long PK
day: Long
lessonTime: Long
}

class Subject{
subjectID: Long PK
timeTableID: Long FK

}

Abstract Class Person{
firstName: String
lastName: String
personID: Long
}

Person *.. Student
Person *.. Teacher
Teacher ||..|{ Subject
TimeTable ||..|{ Subject
Student }|..|| Class
TimeTable ||..|{ Class
Student ||..|{ Absent
Student ||..|| Seat
Subject ||..|| SeatOrder
Seat }|..|| SeatOrder
SeatOrder }|..|| Room


@enduml


