#### Authenticate
POST https://mese.webuntis.com/WebUntis/jsonrpc.do?school=htbla linz leonding
Content-Type: application/json

{
  "id": "ID",
  "method": "authenticate",
  "params": {
    "user": "swifttest",
    "password": "ST.Login19"
  },
  "jsonrpc": "2.0"
}

#### GetKlassen

POST https://mese.webuntis.com/WebUntis/jsonrpc.do?school=htbla linz leonding&jsessionid=2BB0EBABAF070244A010BAE5D76989D2
Content-Type: application/json

{
  "id":"ID",
  "method":"getStudents",
  "params": { },
  "jsonrpc":"2.0"
}
